
# All edge functions will be deployed to the "AI Predictions" project by default.
project_id = "xvojivdhshgdbxrwcokx"

[functions.xai-analysis]
verify_jwt = false

[functions.xai-prediction]
verify_jwt = false

[functions.polygon-market-data]
verify_jwt = false

[functions.test-api-connection]
verify_jwt = false

[functions.resolve-predictions]
verify_jwt = false
